### ISSUE TITLE
Proposal: Pre-commit hook

### ISSUE THREAD

**Issue by CSVdB** [ArdanaLabs/danalib#1]
Set up a pre-commit hook which runs `nix run .#lint-haskell`, to automatically run our formatters as well as `hlint` on each commit.

Edit: I fixed the command.

**Comment by nixinator** [comment]
I don't like pre-commit hooks, especially when working on my own branch, and trying out idea's and potential ugly hacks. Then when i'm ready to *PUSH* to remote, then i lint and format it up to be 'nice' to the repo overlords and squash the commits down to something coherent, and bingo, your done.  

The other reason the git tends not to be pure. I know i bang on about purity, but it matters. If you  unsure what purity is then i'm always up for explaining why it matters. In this case

https://discourse.nixos.org/t/git-hook-not-working/16793/8

A global git configuration (impure) really messed with a developers machine. So the less we mess with developers machines, the better.  I'm against kitchen sink developer machines...

 I'm under the strong opinion that this should be done in CI, but i'm open to idea's, I'm often wrong.

**Comment by MatthewCroughan** [comment]
Running arbitrary hooks (code) on a developers machine upon every commit, which produces logs that are not sharable or observable in the same way they are via CI (just clicking a link to Herc CI), is not good, in my opinion. Developers have their own way of running commands on file changes, such as `entr` or `stack`. This is not a good practice, I've never agreed with it. It does not improve the developer experience. At worst, it actually hampers developer experience by colliding and conflicting with their own personal setup. 

Is it so much to tell a developer to run `nix flake check` if they want the results of CI on their own machine? Do we need to force people to use `nix` in this way?

If anyone wants to check locally, they can run
- `nix run .#lint-haskell` 
- `nix flake check`

Why should we force this on people? It will not improve anything, since CI already informs developers of their syntax errors successfully, and with low latency, since CI returns a result in seconds. This is good enough.

PS: Doesn't HLS let you set up hlint integration already? We can provide this.

**Comment by locallycompact** [comment]
Echoing. Bad developer experience. Commits are to save your work, mess around, jump back and forward, share problems and build logs. We have a CI gate for checks.

**Comment by NorfairKing** [comment]
Hi Peeps

This issue has unfolded somewhat unfortunately.

1. The title was supposed to make it clear that this was a proposal, and not a conclusion.
2. The description was supposed to have the right command: `nix run .#lint-haskell` instead of `nix flake check`.
3. The description did not match the command, in a way that made it ambiguous about whether the linters would be run to format code locally or whether they would be run to check that code had been formatted.

Naturally this has led to some misunderstandings and some very valid pushback.

The issue has been reworded since, but I would still like to give some extra details about the matter.


I originally gave Nick a DX cookbook
[dx-cookbook.txt](https://github.com/ArdanaLabs/danalib/files/7960778/dx-cookbook.txt)
 to consider implementing pieces from.
As you can see, the cookbook is rather sparse on details.

The cookbook specifies a few "pre-commit hooks", but the full suggestion that this phrase is shorthand for is more elaborate.
It consists of three parts:

1. Have CI check that formatters have been run.
2. Have a script that lets devs runs formatters such that CI will be happy in 1
3. Set up a pre-commit hook that runs the script.

With something like https://github.com/cachix/pre-commit-hooks.nix, all three are defined together, and 2 and 3 are set up together.
However, only 1 and 2 are important, and in the flake-y way of doing things in this repository, 2 and 3 are separate.
This means that we get to reconsider whether 3 is important to us.
If people feel strongly about not using pre-commit hooks, but instead manually running 2, then I think that's fine.

If we end up reconsidering whether 3 is important to do, we can open a new issue.
I'll close this issue in the meantime, because 1 and 2 are already done.
