### ISSUE TITLE
Nix and shell formatters

### ISSUE THREAD

**Issue by CSVdB** [ArdanaLabs/danalib#2]
Let us include formatters for Nix (nixpkgs-fmt) and shell (shellcheck) in CI.

**Comment by nixinator** [comment]
Just to be clear , this needs to be added to every repo that we CI for , there is no concept of 'adding it to the CI', like you would do with Jenkins.

**Comment by MatthewCroughan** [comment]
We should use [Alejandra](https://github.com/kamadorueda/alejandra) because it uses rnix-lsp to do things like check the amount of function args there are, and indents accordingly. Additionally, we can add rules. It's a more promising tool than the more primitive nixpkgs-fmt/nixfmt. Shellcheck can be implemented in Nix, by using `writeShellApplication`, which will automatically run shellcheck for us.

**Comment by nixinator** [comment]
This is quite a new tool, but it looks promising. You can see a demo here. Not sure if it's rule based , but even if it's not, it may better than nothing.

https://kamadorueda.github.io/alejandra/


the demo pretty impressive web app in it's own right.

**Comment by CSVdB** [comment]
Looks good to me. @nixinator or @DarthPJB could you integrate it with danalib and make all our packages use the latest danalib version?

**Comment by MatthewCroughan** [comment]
@CSVdB Yup. On the to-do list. Standby.

**Comment by nixinator** [comment]
I need to review the status of this.

**Comment by DarthPJB** [comment]
I'm going to be punching on this today; hopefully with a little progress.

**Comment by nixinator** [comment]
Yeah, linter a day , keeps untidy code away.
